spring:
  application:
    name: fos-producer
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
  threads:
    virtual:
      enabled: true

server:
  port: 8081

fos:
  topics:
    placed: food.orders.placed
    status-updated: food.orders.status-updated
    cancelled: food.orders.cancelled
    dlq: food.orders.dlq
